language: scala
scala:
- 2.12.10
sudo: false
jdk:
- openjdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION router/test compilerServer/test
- sbt ++2.11.12 compilerServer/test

# Set up caches, taken from
# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
